### ISSUE TITLE
Backend fails to start

### ISSUE THREAD

**Issue by derekburgess** [jerlendds/osintbuddy#53]
The console output:

```
osintbuddy-backend-1       | Traceback (most recent call last):
osintbuddy-backend-1       |   File "/app/app/backend_pre_start.py", line 6, in <module>
osintbuddy-backend-1       |     from app.db.session import SessionLocal
osintbuddy-backend-1       |   File "/app/app/db/session.py", line 5, in <module>
osintbuddy-backend-1       |     from app.core.config import settings
osintbuddy-backend-1       |   File "/app/app/core/config.py", line 76, in <module>
osintbuddy-backend-1       |     settings = Settings()
osintbuddy-backend-1       |                ^^^^^^^^^^
osintbuddy-backend-1       |   File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
osintbuddy-backend-1       |   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
osintbuddy-backend-1       | pydantic.error_wrappers.ValidationError: 1 validation error for Settings
osintbuddy-backend-1       | SENTRY_DSN
osintbuddy-backend-1       |   object of type 'NoneType' has no len() (type=type_error)
osintbuddy-backend-1       | INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
osintbuddy-backend-1       | INFO  [alembic.runtime.migration] Will assume transactional DDL.
osintbuddy-backend-1       | Traceback (most recent call last):
osintbuddy-backend-1       |   File "/app/./app/initial_data.py", line 3, in <module>
osintbuddy-backend-1       |     from app.db.init_db import init_db
osintbuddy-backend-1       |   File "/app/app/db/init_db.py", line 3, in <module>
osintbuddy-backend-1       |     from app.core.config import settings
osintbuddy-backend-1       |   File "/app/app/core/config.py", line 76, in <module>
osintbuddy-backend-1       |     settings = Settings()
osintbuddy-backend-1       |                ^^^^^^^^^^
osintbuddy-backend-1       |   File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
osintbuddy-backend-1       |   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
osintbuddy-backend-1       | pydantic.error_wrappers.ValidationError: 1 validation error for Settings
osintbuddy-backend-1       | SENTRY_DSN
osintbuddy-backend-1       |   object of type 'NoneType' has no len() (type=type_error)
osintbuddy-backend-1 exited with code 1
```

**Comment by jerlendds** [comment]
Thanks for catching this! As discussed on discord sentry falsely advertises support for Python 3.11 and when I removed that last night I forgot to also update the backend apps `config.py` settings. I've pushed a fix and it should be working now
